name: CI Pipeline

on:
  pull_request:
  push:
    branches: [main, master]

permissions:
  contents: read

jobs:
  quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Configure Poetry for CI
      run: |
        poetry config virtualenvs.create false

    - name: Install dependencies
      run: |
        poetry install --with dev --with test --all-extras

    - name: Run pre-commit hooks
      run: |
        poetry run pre-commit run --all-files

    - name: Run security checks
      run: |
        poetry run bandit -r bizon/

    - name: Run type checking
      run: |
        poetry run mypy bizon/ || true  # Allow to fail initially

  test:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    container: python:3.10

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: bizon
          POSTGRES_DB: bizon_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d bizon_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
    - uses: actions/checkout@v4

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Configure Poetry for CI
      run: |
        poetry config virtualenvs.create false

    - name: Install dependencies
      run: |
        poetry install --with test --all-extras

    - name: Run tests with coverage
      run: |
        POETRY_ENV_TEST=CI poetry run pytest tests/ --cov=bizon --cov-report=xml --cov-report=term-missing
      env:
        # The hostname used to communicate with the PostgreSQL service container
        POSTGRES_HOST: postgres
        # The default PostgreSQL port
        POSTGRES_PORT: 5432

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella